# dataset parameters
dataset_type: "BurgersDataset"
dataset_root: "dataset/burger"

# experiment configs
test_res_pair: [[0, 3]]
log_dir: "runs/exp_1_burger"
model_dir: "checkpoints/exp_1_burger/TEECNet"
