# dataset parameters
dataset_type: "MegaFlow2D"
dataset_root: "dataset/reduced_megaflow"

# model parameters
model_type: "NeuralOperator"
in_channel: 5
out_channel: 3
width: 64
num_layers: 4
dropout: 0.5

# experiment configs
train_res_pair: [[0, 1]]
test_res_pair: [[0, 2]]
log_dir: "runs/exp_1_megaflow"
model_dir: "checkpoints/exp_1_megaflow"
