# dataset parameters
dataset_type: "BurgersDataset"
dataset_root: "dataset/burger"

# model parameters
model_type: "GraphSAGE"
in_channel: 1
out_channel: 1
width: 128
num_layers: 6
dropout: 0.5
num_powers: 3

# experiment configs
train_res: [0, 3]
# test_res: [[0, 2], [0, 3], [1, 2], [1, 3], [2, 3]]
log_dir: "runs/exp_2_burger"
model_dir: "checkpoints/exp_2_burger"
