# dataset parameters
dataset_type: "MegaFlow2D"
dataset_root: "dataset/reduced_megaflow"

# model parameters
model_type: "TEECNet"
in_channel: 1
out_channel: 1
width: 16
num_layers: 3
num_powers: 2

# experiment configs
train_res_pair: [[0, 1]]
test_res_pair: [[0, 2]]
log_dir: "runs/exp_1_megaflow"
model_dir: "checkpoints/exp_1_megaflow/increased_range"
