# dataset parameters
dataset_type: "HeatTransferDataset"
dataset_root: "dataset/heat"

# model parameters
model_type: "NeuralOperator"
in_channel: 1
out_channel: 1
width: 64
num_layers: 6
dropout: 0.5

# experiment configs
train_res_pair: [[0, 1], [0, 2], [0, 3], [1, 2], [1, 3], [2, 3]]
test_res_pair: [[0, 2], [0, 3], [1, 2], [1, 3], [2, 3]]
log_dir: "runs/exp_1_heat"
model_dir: "checkpoints/exp_1_heat"
