# dataset parameters
dataset_type: "BurgersDataset"
dataset_root: "dataset/burger"

# model parameters
model_type: "TEECNet"
in_channel: 2
out_channel: 2
width: 16
num_layers: 3

# experiment configs
train_res_pair: [[0, 3]]
test_res_pair: [[0, 3]]
log_dir: "runs/exp_1_burger"
model_dir: "checkpoints/exp_1_burger"
