# dataset parameters
data_dir: "C:/research/data"
split_scheme: "full"
split_ratio: [1, 1]
transform: 

# model parameters
model_name: "CFDErrorInterpolate"
in_channel: 3
out_channel: 3

# training parameters
loss: "MSELoss"
metric: "r2_score"
epochs: 500
batch_size: 64
learning_rate: 0.00084