# dataset parameters
data_dir: "C:/research/data"
split_scheme: "developed"
split_ratio: [1, 1]
transform: 

# model parameters
model_name: "CFDErrorInterpolate"
in_channel: 3
out_channel: 3

# training parameters
loss: "VorticityLoss"
metric: "r2_score"
epochs: 150
batch_size: 64
learning_rate: 0.00084
weight_decay: 0.001