# dataset parameters
data_dir: "C:/research/data"
split_scheme: "full"
split_ratio: [1, 1]
transform: "normalize"

# model parameters
model_name: "CFDErrorInterpolate"
in_channel: 3
out_channel: 3

# training parameters
loss: "MSELoss"
metric: "norm_divergence"
epochs: 1000
batch_size: 32
learning_rate: 0.00084